FROM python:3.12-slim

RUN pip install uv

WORKDIR /app
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-dev

COPY src/ ./src/

EXPOSE 8000
CMD ["uv", "run", "fastapi", "run", "src/api/main.py", "--port", "8000", "--host", "0.0.0.0"]
