FROM node:20-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 python3-pip curl git \
    && rm -rf /var/lib/apt/lists/*

# AWS CDK CLI
RUN npm install -g aws-cdk ts-node typescript

WORKDIR /app

CMD ["/bin/sh"]
